{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "rnn_units", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "rmsprop"], "ordered": false}}, {"class_name": "Int", "config": {"name": "rnn_units_1", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "rnn_units_2", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "rnn_units_3", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 16, "sampling": "linear"}}], "values": {"rnn_units": 64, "optimizer": "adam", "rnn_units_1": 32, "rnn_units_2": 32, "rnn_units_3": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 270, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 235, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 307, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 226, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 158, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 149, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"/home/sr-souza/Desktop/TCC-AI/src/models_regression.py\", line 50, in build_rnn_model\n    model.add(SimpleRNN(units=hp.Int('rnn_units_3', min_value=32, max_value=128, step=16)))\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/tensorflow/python/trackable/base.py\", line 204, in _method_wrapper\n    result = method(self, *args, **kwargs)\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/sr-souza/.local/lib/python3.10/site-packages/keras/src/engine/input_spec.py\", line 235, in assert_input_compatibility\n    raise ValueError(\nValueError: Input 0 of layer \"simple_rnn_2\" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 32)\n"}